# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='\u7528\u6237')),
                ('password', models.CharField(max_length=64, verbose_name='\u5bc6\u7801')),
            ],
        ),
    ]
